### ISSUE TITLE
Cannot run via go script

### ISSUE THREAD

**Issue by andeemarks** [andrewh42/ten-times-developer#1]
I think I have the deps right, but no output is produced and the go script seemed to run wayyy too quickly.

```bash
$  java --version
openjdk 11.0.4 2019-07-16
OpenJDK Runtime Environment (build 11.0.4+11-post-Ubuntu-1ubuntu218.04.3)
OpenJDK 64-Bit Server VM (build 11.0.4+11-post-Ubuntu-1ubuntu218.04.3, mixed mode, sharing)
$  python --version
Python 2.7.15+
$  ./go 
Installing the Z3 prover:
  - building the C++ library and Scala binding 
$
```

**Comment by andrewh42** [comment]
Did a previous ./go download sbt or do you have one already installed? A too-old sbt could potentially be a problem.

**Comment by andrewh42** [comment]
Thanks @andeemarks. It's probably due to your Mac not having a clang++ installed. I've added Xcode command line tools to the prerequisites mentioned in the README and improved the go script's error reporting: please do a `git pull` to grab those and let me know how you go!

**Comment by andeemarks** [comment]
I'm running Mint Linux.  I'll pull and see what happens and also make sure I've removed any old SBT installs
